package exceptionHandling;

import java.io.IOException;

public class TestClass {

	public static void main(String[] args) throws IOException 
	{
		//throw new ArithmeticException();
		
		/*int a=0;
		int b=20;
		
		System.out.println(b/a);

		System.out.println("Anand");*/
		
		fun2();
		
		throw new IOException();
	}
	
	public static void fun1()
	{
		throw new ArithmeticException();
	}

	public static void fun2() 
	{
		try {
			throw new IOException();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}
